use core::{
	time::Duration,
};

pub mod clamp;
pub use clamp::clamp;
pub mod error;
pub use error::{Error, Result};


pub enum SlotTime {
	UserSpecified(Duration),
	AutoGenerated(Duration),
}

pub type ExecutionResult = Result<()>;
